---
title: "SKS104_Midterm"
author: "Skasko_Stephen"
date: "10/11/2023"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

```{r}
library(readxl)
library(plotly)
library(fpp)
library(astsa)
library(latex2exp)
library(ggplot2)
library(forecast)
library(Ecdat)
library(TSstudio)
library(stats)
library(TSA)
```

#1
```{r}

unemployment = read.csv("Unemployment.csv")

# a)
a = ts(unemployment$Unemployment.Rate, start = 2010, f = 4)
print(a)

# b)
plot(a, main = "Unemployment Time Series", xlab = "Year", ylab = "Unemployment Rate in IS (in %)", type = "o")

# c) 

# The plot displays a downward trend from 2010-2020 for unemployment rates. When looking at the plot through a quarterly lens, there tends to be some seasonality to it when you took it by the 4 seasons (Winter, Spring, Summer, Fall). There is a slight spike when hitting the Winter months then it gradually declines. Based on the plot and data we have, there may not be any cyclicity since it doesn't follow a pattern or irregularity over years and more in quarters of a year. 

# d) 

# The plot shows 4 different bars that follow quarterly for each lag. In plot 1, there seems to be similar to the previous one, meaning there is a downward trend with seasonality in the lags. With this, there tends to be consistency and not following a cyclicity pattern too. 

acf(a, main = "ACF Plot for Unemployment Rate")

# e)
t = seq(1, length(time(a)), by = 1)
s = season(a)

model = lm(a ~  s + t - 1)
summary(model)


# f) 

# The plot has many data points in a downward trend, while the fitted line shows us how closely related the data points are. Based on the fitted model that closely relates with the data points in a consistent trend then it does imply a strong model fit for the data. 

plot(a,main = "Unemployment Time Series in F", xlab = "Year", ylab = "Unemployment Rate in (in %)", type = "p")
lines(as.vector(time(a)), fitted(model), type = "l",col="blue") 

# g) 

# Based on the linear trend, the coefficients are in a downward constant trend, which could mean that there is a correlation between the policies implemented and years of unemployment throughout 2010-2020. Similarly, there could be a correlation between presidential candidates having good economic years like Obama from 2009-2017, then Trump from 2017-2021. Of course, this is all before COVID-19 hit the job market badly . Another way to interpret it is that overtime, the unemployment rate has decreased, potentially from the economy getting slightly better over time in the USA. With this, the coefficients are 

print(coef(model))
# y = B_0 + B_1sqQ1 + B_2sqQ2 + B4sqQ3 + B_4sqQ4 + B_5t + e 

# or can be shown as:

# y = B_0 + 10.27sqQ1 + 9.80sqQ2 + 10.05sqQ3 + 9.73sqQ4 - 0.18t

# h) 

# Based on the model, the unemployment rate mostly decrease slightly when moving from the second quarter to the third quarter but it also shows the opposite with increasing slightly. Additionally, based on the model, it generally seems to increase slightly and decrease slightly by approximately 0.01 (1%) or 0.02 (2%). 

# i)

# Based on the plot, there tends to be no seasonality since there is no trend regarding periods of seasons or quarterly. With this, there may be a trend where the percentage drops every 7 years but then there is an irregular drop and increase from 14 to 40 years. Before the irregularly, there tends to be a potential cyclicity trend that may occur. So, out of the 4, there may be trend, Cyclicity and Irregularity. 

r = residuals(model)
plot(r,main = "Residuals Time Series", xlab = "Year", ylab = "Unemployment Rate in IS (in %)", type = "o")


# j)

# Yes, the plot does show autocorrelation by the consistency of the plot for each lag. One big indicator was lag 5 being 0.1 and lag 10 being -0.1. This could definitely indicate a cyclicity trend. Since we have a constant autocorrelation, this convey that there was an economic boom and lots of people were working in the market. Additionally, the lags can convey that employment rates correlate with previous years, meaning the policy changes or other factors done years ago.  

acf(r, main = "ACF Plot for Residuals")

```

\newpage
#2
```{r}

set.seed(1000)

n = 502
wt = rnorm(n, 0, sqrt(4))
xt_a = numeric(n)
xt_b = numeric(n)
xt_c = numeric(n)



#500 observations 
for (i in 3:n) {
  xt_a[i] = 0.7 * xt_a[i-1] + wt[i]
  xt_b[i] = -0.7 * xt_b[i-1] + wt[i]
  xt_c[i] = wt[i] - 0.5*wt[i-1] 

}


xt_ap = stats::filter(xt_a, c(1, 0.7), sides = 1)
xt_bp = stats::filter(xt_b, c(1, -0.7), sides = 1)
xt_cp = stats::filter(xt_c, c(1, -0.5), sides = 1)


xt_ao = na.omit(xt_ap)
xt_bo = na.omit(xt_bp)
xt_co = na.omit(xt_cp)


acf(xt_ao, main = "ACF for X_t = 0.7X_t−1 + W_t")
acf(xt_bo, main = "ACF for X_t = -0.7X_t−1 + W_t")
acf(xt_co, main = "ACF for X_t = W_t - 0.5W_t-1")


# e) 

# The plots show similarities by having high drops in the first few years then shows consistently after about 10 lags. With this, the plot tends to stay around 0.1 or -0.1 after lag 10 in both plots. The key difference in the plots is one slowly decreases overtime in same direction, while the other one jumps up/down from positive to negative before getting smaller. Similarly, one graph shows more predictability compared to the other plot showing erratic jumps between positive and negative values. Lastly, it may tell us that there may be a pattern with seasonality.  

# f) 

# Main difference is not having X_t in the formula for time and filter function uses (1, -0.5) instead of the (1, 0.7)
```

