---
title: "SKS104_HW3"
author: "Skasko_Stephen"
date: "10/29/2023"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
# 4
```{r}
library(stats)
set.seed(1000)
n <- 1:100

model_a <- c(0.6, 0.3)
model_b <- c(-0.4, 0.5)
model_c <- c(1.2, -0.7)
model_d <- c(-1, -0.6)

acf_a <- ARMAacf(ar = model_a, lag.max = 12)
acf_b <- ARMAacf(ar = model_b, lag.max = 12)
acf_c <- ARMAacf(ar = model_c, lag.max = 12)
acf_d <- ARMAacf(ar = model_d, lag.max = 12)

sim_a <- stats::filter(rnorm(100), filter = model_a, method = "recursive")
sim_b <- stats::filter(rnorm(100), filter = model_b, method = "recursive")
sim_c <- stats::filter(rnorm(100), filter = model_c, method = "recursive")
sim_d <- stats::filter(rnorm(100), filter = model_d, method = "recursive")

plot(n, sim_a, type = "l", main = "Simulated Data for Model (a)", xlab = "Time", ylab = "Simulated Value")
plot(n, sim_b, type = "l", main = "Simulated Data for Model (b)", xlab = "Time", ylab = "Simulated Value")
plot(n, sim_c, type = "l", main = "Simulated Data for Model (c)", xlab = "Time", ylab = "Simulated Value")
plot(n, sim_d, type = "l", main = "Simulated Data for Model (d)", xlab = "Time", ylab = "Simulated Value")

acf_a
acf_b
acf_c
acf_d
```

\newpage


# 5
```{r}
# a)
library(TSA)
library(plotly)

data(prescrip)

ts_data <- ts(prescrip, start = c(1986, 8), f = 12)
plot(ts_data, main = "Monthly US Prescription Costs", ylab = "Cost", xlab = "Time")

# Describe: The plot does potentially indicate seasonality since there is a consistent and steady fluctuation every few years/cost over time. Some key pointers in the plot show a higher increasing cost steadily around the spring into summer but then drops towards fall into winter months. Also, there may be potential for cyclicity based on periods of the trend in similarities with dips around the end of each year.     

# b)
t <- seq(1, length(prescrip), by = 1)
t_sq <- t^2
harmonic_model <- lm(prescrip ~ t + sin(2 * pi * t/12) + cos(2 * pi * t/12) + t_sq)
summary(harmonic_model)

temp_df <- data.frame(time = time(ts_data), ts_data, fitted_values = fitted(harmonic_model))

#### ~Data helps to show relationship between the dependent and independent variables in a model ####
plot_ly(temp_df, x = ~time) %>%
  add_markers(y = ~ts_data, name = "Original Data") %>%
  add_lines(y = ~fitted_values, name = "Fitted Curve") %>%
  layout(yaxis = list(title = "Monthly US Prescription Costs"), xaxis = list(title = "Time"))

# c)
residuals <- residuals(harmonic_model)
plot(residuals, type = "l", ylab = "Residuals", xlab = "Time", main = "Residual Plot from Harmonic Regression Model")

# Describe: Although not too noticeable, there may be a subtle trend happening where we have two high peaks then decreases over a period of time. Based on this, there may be potential for cyclicity in the model over time. An interesting point at the high peak of over 1.0 in the y-axis of residuals. Also, the lowest point is interesting at -1.5 residual y-axis, which is both within the time span of 60 to 70. From these finding, the one thing showing is how much variability is going on in the plot.     

# d) 
acf(residuals, main = "ACF of Residuals")

# Describe: The plot seems to show a trend pattern. Additionally, it seems very constant and with low variability, along with a potential for seasonality. Based on the consistency but a little bit unstable in certain parts, there could be a potential for a little white noise. Also, most of the points fall within the blue lines parameters, which could indicate a trend as well, where the highest peak is 0.4 with a lowest at -0.4.  

# e)
hist(residuals, main = "Histogram of Residuals", xlab = "Residuals", ylab = "Frequency")

# Describe: The histogram looks to be normally distributed with even tails. One interesting thing is how far up the third and fourth bar is compared to the rest but still follows a normal distribution. The center peak is at around 25-30 frequency, while the lowest is at around around 1 frequency. Based on this, it may suggest potential for variability and skewness in the data.  

# f)
ts_data_model <-  window(prescrip, start = c(1986, 8), end = c(1992, 3))
quart <- season(ts_data_model) 
t_prescrip <- seq(1,length(ts_data_model), by=1)

seasonal_model <- lm(ts_data_model ~ quart + t_prescrip-1)


harmonic_AIC <- AIC(harmonic_model)
harmonic_BIC <- BIC(harmonic_model)
harmonic_Rsquared <- summary(harmonic_model)$r.squared

seasonal_AIC <- AIC(seasonal_model)
seasonal_BIC <- BIC(seasonal_model)
seasonal_Rsquared <- summary(seasonal_model)$r.squared


cat("Harmonic Regression Model:\n")
cat("AIC:", harmonic_AIC, "\n")
cat("BIC:", harmonic_BIC, "\n")
cat("R-squared:", harmonic_Rsquared, "\n\n")

cat("Seasonal Means Model:\n")
cat("AIC:", seasonal_AIC, "\n")
cat("BIC:", seasonal_BIC, "\n")
cat("R-squared:", seasonal_Rsquared, "\n")


# g)

# Model: Harmonic model seems to be a better-performing model based on the lower values of BIC and AIC.

```

\newpage

# 6
```{r}
# a) 
library(ggplot2)
library(lubridate)
library(plotly)


AAPL <- read.csv("AAPL.csv")
AAPL$Date <- as.Date(AAPL$Date)

plot_ly(AAPL, x = ~Date, y = ~Close, type = 'scatter', mode = 'l') %>%
  layout(title = "Apple Closing Prices", xaxis = list(title = "Date"), yaxis = list(title = "Closing Price"))

# Describe Plot: The plot may show some type of trend with prices, where price drops from August/October till December then begins to increase after January. This could imply seasonality based on certain months of the year with a steady and hard declines in November to December and pivots back up a lot from January to July. Also, this may indicate cyclicity with the regular trends and dips within the certain month periods in October and November, but unsure with the limited data of a one year period. 



# b) 
acf(AAPL$Close, main = "ACF Plot for Closing Prices")

# Describe Plot: The lag plot shows a very slow but steady decline from 0.9 to 0.8, which could indicate a decreasing trend. This could indicate a weak relationship over time with little to no white noise.   



# c)
diff <- diff(AAPL$Close, differences = 1)
ts_diff <- ts(diff, f = 12)
acf(ts_diff, main = "ACF Plot for First Order Differenced Closing Prices")

# Describe Plot: The plot seems to show a trend with the bigger values at -0.10 and smallest at 0.01. The trend pattern may indicate a potential for seasonality and some white noise. 


# d) 

# Potentially ARIMA model of AR(1).  

```
\newpage

# 7
```{r}
# a)
library(forecast)

wine_sales <- read.csv("wine_sales.csv")


ts_data <- ts(wine_sales$X7006, start = c(1985, 3), f = 4)
plot(ts_data, type = "l", main = "Wine Sales over Time", xlab = "Date", ylab = "Sales")

# Describe: Based on the plot, it is stable and consistent downward trend with cyclic behavior. From this, the additive model would be best to use with its consistency. 

# b)
t_ap <- seq(1, length(ts_data), by = 1)
t_ap_sq <- t_ap^2
additive_model <- lm(ts_data ~ t_ap + t_ap + t_ap_sq + season(ts_data))
summary(additive_model)

AP_df <- data.frame(time(ts_data), ts_data) 

AP_df %>% 
  plot_ly(x = ~time(ts_data), showlegend = T) %>%
  add_trace(y = ~ts_data, mode = "lines", type = "scatter", name = "Original Data") %>%
  add_trace(y = ~fitted(additive_model), mode = "lines", type = "scatter", name = "Fitted Curve") %>%
  layout(yaxis = list(title =  "Sales"), xaxis = list(title = "Date"))

# c)
multiplicative_model <- lm(log(ts_data) ~ t_ap + t_ap + t_ap_sq + season(ts_data))
summary(multiplicative_model)

AP_df %>% 
  plot_ly(x = ~time(ts_data), showlegend = T) %>%
  add_trace(y = ~ts_data, mode = "lines", type = "scatter", name = "Original Data") %>%
  add_trace(y = ~exp(fitted(multiplicative_model)), mode = "lines", type = "scatter", name = "Fitted Curve") %>%
  layout(yaxis = list(title =  "Sales"), xaxis = list(title = "Date"))

# d) 
acf(residuals(additive_model), main = "ACF Plot of Residuals - Additive Model")
acf(residuals(multiplicative_model), main = "ACF Plot of Residuals - Multiplicative Model")

checkresiduals(additive_model$residuals)
checkresiduals(multiplicative_model$residuals)

# e) 

# Answer: Based on the models, the additive model performs better since it shows a constant and steady trend, little to no white noise, and a more evenly normal distribution 

```

