---
title: "SKS104_HW4"
author: "Skasko_Stephen"
date: "12/2/2023"
output: html_document
---

```{r}
library(forecast)
library(plotly)
library(TSA)
library(tseries)


JJ <- read.csv("JJ.csv")
boardings <- read.csv("boardings.csv")

```
\newpage

# 4
```{r}
set.seed(1)

simulated_data <- arima.sim(model = list(order = c(2, 1, 2), ar = c(0.6, -0.4), ma = c(-1, 0.5)), n = 250)

plot(simulated_data, type = "l", lwd = 2, pch = 16,
     xlab = "Time", ylab = "Simulated Data",
     main = "Simulated Time Series Plot")


acf(simulated_data, main = "ACF Plot for Simulated Data")
pacf_plot <- pacf(simulated_data, main = "PACF Plot for Simulated Data")

# a - The model seems to be based on a SARIMA model with an order of (2, 0, 2)*(1, 0, 1).
# b - The plot seems to show a downward trend with a few sudden drops (around 125 & 225) as it moves back to a jumping pattern. Based on plot, there could be some cyclicity but no seasonality.
# c - The AFC plot shows a slow moving downward trend starting at 1.0 over lags, where lags are all showing the ACF lags over the blue lines at 0.1, which could indicate a MA model. Unlike the AFC plot, the PACF shows the first lag at 1.0 with blue lines at 0.1. After the first lag, the PACF plot shows small lags under 0.1 with a slight trend as the lags grow slightly smaller overtime with lags moving from positive to negative continuously. The results could tell us that the model is an AR(1) model.
```
\newpage

# 5
```{r}
# a) - The first plot shows a slowly increasing trend as it grows larger overtime for earnings, while the transformed plot shows a jumps a bit more consistently with a clearer pattern overtime. These results indicate its best to use logs with the consistent and stable, and with the ease of the stabilization overtime with the trend.  


ts_original <- ts(JJ$X0.71, frequency = 4, start = c(1960, 1))

plot(ts_original, main = "Original Time Series A", ylab = "Earnings")
ts_log <- log(ts_original)
plot(ts_log, main = "Log Transformed Time Series A", ylab = "Log(Earnings)")


# b - Based on the plot, it does show a steady and consistent trend, which could indicate a stationary series. Additionally, the second plot gives a much better look into stationary since there is a consistent trend but with the ability to see the a clear pattern. 
plot(ts_log, main = "Log Transformed Time Series B", ylab = "Log(Earnings)")
ts_diff <- diff(ts_log)
plot(ts_diff, main = "First Difference of Log Transformed Series B", ylab = "Differenced Log(Earnings)")



# c - The ACF log plot shows a consistent downward trend overtime with high lags with the initial blue lines at -0.2 and 0.2. Also, the plot shows consistency and stability, which could indicate a MA process. The difference plot shows a slowly decreasing trend with high lags and small lags moving from positive to negative repeatedly by one each time, which indicates a pattern.  
acf(ts_log)
title("ACF of Log Transformed Series C")
acf(ts_diff)
title("ACF of First Difference Series C")

# d - The plot shows a very jumpy pattern overtime where it has a consistent pattern, but has a potential for cyclicity since it jumps small to larger and then to small again over a period of time. 
ts_seasonal_diff <- diff(ts_diff, lag = 4)
plot(ts_seasonal_diff, main = "Seasonal Difference of First Difference Series D", ylab = "Seasonal Differenced Log(Earnings)")

# e
acf_twice_diff <- acf(diff(ts_diff), plot = FALSE)
acf(diff(ts_diff))
title("ACF of Twice Differenced Series E")

pacf(diff(ts_diff))
title("PACF of Twice Differenced Series E")


# f - Based on the plots, I would potentially suggest is SARIMA(1,1,1)(0,1,1) or SARIMA(1,1,2)(1,1,1). 
acf_diff_twice <- acf(diff(ts_diff, lag = 4), main = "ACF of Twice Differenced Series F")
pacf_diff_twice <- pacf(diff(ts_diff, lag = 4), main = "PACF of Twice Differenced Series F")

# g
best_model <- auto.arima(ts_diff, allowdrift = FALSE)
summary(best_model)

# h 
sarima_model <- Arima(ts_log, order = c(0, 1, 1), seasonal = list(order = c(0, 1, 1), period = 4))
summary(sarima_model)

# i 
checkresiduals(sarima_model)

# j
forecast_values <- forecast(sarima_model, h = 8)
plot(forecast_values)


```
\newpage

# 6
```{r}
ts_boardings <- ts(boardings$X12.49114, start = c(2000, 8), frequency = 12)
plot(ts_boardings, main = "Time Series Plot of Log Boardings A", ylab = "Log Boardings")


# a - Based on the plot, there seems to be a little to no consistency, which could indicate a non-stationary series. After doing the hypothesis tests, there is a p-value of 0.51, which could give us more clear idea on the series being non-stationary.  
adf_test <- adf.test(ts_boardings)
adf_test

# b - On the ACF plot, the large lags are at 0.1 and 1.0, while the PACF plot shows high lags at 0.5, 1.0, and 1.1. 
acf(ts_boardings, main = "ACF of Log Boardings B")
pacf(ts_boardings, main = "PACF of Log Boardings B")

# c - Based on the plots, the recommended SARIMA model could be SARIMA(1,1,0)*(1,1,1,12). 

# d - Used the summary function for accessing the coefficients. 
arma_model <- Arima(ts_boardings, order = c(0, 0, 3), seasonal = list(order = c(1, 0, 0), period = 12))
summary(arma_model)

# e - The auto.arima function suggests a different but potentially better model (ARIMA(0,1,3)(0,1,1)[12]) for the data compared to the model you specified in part (d). This new model has lower values for AIC and BIC, indicating improved performance according to these criteria and making it a recommended choice for modeling the time series data.
auto_arima_model <- auto.arima(ts_boardings, seasonal = TRUE, stepwise = FALSE, approximation = FALSE)
summary(auto_arima_model)
```

