---
title: "Homework 8 Code"
output:
  html_document:
    df_print: paged
---

Read in and clean data for Problem 1

```{r}

ncaab_scores <- read.table("2018_ncaab.csv", header = TRUE, sep = ",")
teams <- read.table("2018_tournament_teams.csv", header = TRUE, sep = ",")

ncaab_scores$home_team = gsub(" ", ".", ncaab_scores$home_team)
ncaab_scores$away_team = gsub(" ", ".", ncaab_scores$away_team)
ncaab_scores$home_team = gsub("-", "_", ncaab_scores$home_team)
ncaab_scores$away_team = gsub("-", "_", ncaab_scores$away_team)
ncaab_scores$home_team = gsub("&", "", ncaab_scores$home_team)
ncaab_scores$away_team = gsub("&", "", ncaab_scores$away_team)

```

Problem 1a

```{r}
teams = sort(unique(ncaab_scores$home_team))

ncaa_data = as.data.frame(matrix(nrow = nrow(ncaab_scores), ncol = 2 + length(teams)))

colnames(ncaa_data) = c("MoV", "Location", teams)

ncaa_data[is.na(ncaa_data)] = 0


for (i in 1:length(teams)) {   
    home = as.integer(ncaab_scores$home_team == teams[i])     
    away = -1*as.integer(ncaab_scores$away_team == teams[i])  
    team_locations = home + away                            
    ncaa_data[, i+2] = team_locations                     
}

ncaa_data$MoV = ncaab_scores$home_score - ncaab_scores$away_score

ncaa_data$Location = ncaab_scores$location


model = lm(MoV ~ 0 + ., data = ncaa_data)

coefficients = coef(model, complete = TRUE)
coefficients[length(coefficients)] = 0
adjustment = -1 * sum(coefficients[2:length(coefficients)]) / (length(coefficients) - 1)

ratings = c(coefficients[1], coefficients[2:length(coefficients)] + adjustment)

bt_coefficients <- coefficients

baseline_team <- names(bt_coefficients)[which.max(abs(bt_coefficients))]
baseline_rating <- bt_coefficients[baseline_team]
bt_coefficients <- bt_coefficients - baseline_rating

print(head(bt_coefficients, 10))

residual_standard_error <- sigma(model)
print(residual_standard_error)

```

Problem 1b

```{r}
home_coefficient <- coefficients[length(coefficients)]
adjusted_ratings <- coefficients - home_coefficient
print(head(adjusted_ratings, 10))
```

Problem 1c

```{r}
set.seed(31) 
iterations = 10000  
num_teams = 64  
league_sd = sigma(model)  

tournament_teams = read.table("2018_tournament_teams.csv", header = TRUE, sep = ",")
tournament_teams$team = gsub(" ", ".", tournament_teams$team)
tournament_teams$team = gsub("-", "_", tournament_teams$team)
tournament_teams$team = gsub("&", "", tournament_teams$team)

results = matrix(0, iterations, num_teams-1)  

tournament_ratings = data.frame(matrix(ncol = 10, nrow = num_teams))
colnames(tournament_ratings) = c("team", "seed", "region", "rating", "R32", "SS", "EE", "FF", "CG", "Champ")

tournament_ratings$team = tournament_teams$team
tournament_ratings$seed = tournament_teams$seed
tournament_ratings$region = tournament_teams$region

for(i in 1:num_teams) {
  tournament_ratings$rating[i] = as.numeric(ratings[tournament_teams$team[i]])
}

for(i in 1:iterations) {
    current_round = tournament_teams$team    
    next_round = NULL    
    winners = NULL      
    while(length(current_round) > 1) {  
        for(j in 1:(length(current_round)/2)) {  
            team_1 = current_round[2*j-1]  
            team_2 = current_round[2*j]    
    
            r1 = ratings[team_1]
            r2 = ratings[team_2]
            
            win_prob = 1 - pnorm((0-(r1-r2))/league_sd, 0, 1)  
            u = runif(1, 0, 1)
            
            # Determine winner of current game
            if(u < win_prob) {
                next_round = c(next_round, team_1)
            } else {
                next_round = c(next_round, team_2)
            }
        }
    
        current_round = next_round    
        winners = c(winners, next_round) 
        next_round = NULL   
    }
    results[i,] = winners  
}

for(i in 1:num_teams) {  # For each team in the tournament
    tournament_ratings$R32[i] = 100 * length(which(results[,1:32] == tournament_teams$team[i]))/iterations
    tournament_ratings$SS[i] = 100 * length(which(results[,33:48] == tournament_teams$team[i]))/iterations
    tournament_ratings$EE[i] = 100 * length(which(results[,49:56] == tournament_teams$team[i]))/iterations
    tournament_ratings$FF[i] = 100 * length(which(results[,57:60] == tournament_teams$team[i]))/iterations
    tournament_ratings$CG[i] = 100 * length(which(results[,61:62] == tournament_teams$team[i]))/iterations
    tournament_ratings$Champ[i] = 100 * length(which(results[,63] == tournament_teams$team[i]))/iterations
}

tournament_ratings = as.data.frame(tournament_ratings)
tournament_ratings
```

Problem 1g

```{r}
michigan_left_side = sum(results[, 61] == "Michigan")

villanova_right_side = sum(results[, 62] == "Villanova")

cat("Michigan appeared in the championship game from the left side:", michigan_left_side, "times\n")
cat("Villanova appeared in the championship game from the right side:", villanova_right_side, "times\n")



# e - The favorite team in the south is Virginia and the probability of making it to the final four in the tournament is 75.27. 
south_teams <- tournament_ratings[tournament_ratings$region == "South", ]
favorite_team <- south_teams[which.max(south_teams$FF), ]

cat("The favorite team in the South region to make the Final Four after Virginia's elimination:", favorite_team$team, "\n")
cat("Probability of making it to the Final Four when the tournament started:", favorite_team$SS, "\n")

# f - Based on the output, the probability of Kansas reaching the Elite Eight is 49.74%, while Florida is 9.71% chance. 

kansas_state_info <- subset(tournament_ratings, team == "Kansas")
florida_state_info <- subset(tournament_ratings, team == "Florida")

prob_kansas_state_elite_eight <- kansas_state_info$EE
prob_florida_state_elite_eight <- florida_state_info$EE

rating_kansas_state <- kansas_state_info$rating
rating_florida_state <- florida_state_info$rating

cat("Probability of Kansas State reaching the Elite Eight:", prob_kansas_state_elite_eight, "\n")
cat("Probability of Florida State reaching the Elite Eight:", prob_florida_state_elite_eight, "\n")

cat("Rating of Kansas State:", rating_kansas_state, "\n")
cat("Rating of Florida State:", rating_florida_state, "\n")



# h - Michigan appeared in the championship 554 times, while Villanova appeared 3214 times. 
michigan_left_side = sum(results[, 61] == "Michigan")
villanova_right_side = sum(results[, 62] == "Villanova")

cat("Michigan appeared in the championship game from the left side:", michigan_left_side, "times\n")
cat("Villanova appeared in the championship game from the right side:", villanova_right_side, "times\n")

```

Read in data for Problem 2

```{r}
simulated_season = 2015

scores = read.table("nba_data.csv", header = TRUE, sep = ",")

team_info = read.table("nba_initial_elos.csv", header = TRUE, sep = ",")

conferences = na.omit(unique(team_info$conference))
divisions = na.omit(unique(team_info$division))

pre_season = scores[which(scores$season < simulated_season & scores$season >= 1901),]

season_schedule = scores[which(scores$season == simulated_season & (scores$game_type == "r" | scores$game_type == "np")),]

hfa = 53.67
weight = 17.9

if (sum(scores$tie) > 0) {
    tie_adj = 0.5 
} else {
    tie_adj = 0
}

for(i in 1:nrow(pre_season)) {
    home_index = which(team_info$team == pre_season$home_team[i])
    away_index = which(team_info$team == pre_season$away_team[i])
    
    home_elo = team_info$rating[home_index]
    away_elo = team_info$rating[away_index]
    

    win_prob = 1 / (10^((away_elo - (home_elo + hfa*pre_season$location[i]))/400) + 1)
    
    score_diff = abs(pre_season$home_score[i] - pre_season$away_score[i])
    
    if(pre_season$home_score[i] > pre_season$away_score[i]) { 
    home_result = 1 
    } else if(pre_season$home_score[i] < pre_season$away_score[i]) { 
    home_result = 0  
    } else { 
    home_result = 0.5 
    }
    
    home_elo_adjustment = weight * log(score_diff + 1 + tie_adj) * (home_result - win_prob)

  
    team_info$rating[home_index] = team_info$rating[home_index] + home_elo_adjustment
    team_info$rating[away_index] = team_info$rating[away_index] - home_elo_adjustment
    
    if(i < nrow(scores) && scores$season[i+1] > scores$season[i]) {
        for(j in 1:nrow(team_info)) {
            if(scores$season[i] >= team_info$inaugural_season[j]) {
                team_info$rating[j] = team_info$rating[j] - (team_info$rating[j] - 1500)/3
                }
        }
    
        existing_teams = team_info[which(team_info$inaugural_season <= (scores$season[i] + 1)),]
    
        expansion_adjustment = -1*(mean(existing_teams$rating) - 1500)
    
        for(j in 1:nrow(team_info)) {
            if((scores$season[i] + 1) >= team_info$inaugural_season[j]) {
                team_info$rating[j] = team_info$rating[j] + expansion_adjustment
            }
        }
    }
}
set.seed(37)

iterations = 1000

results = data.frame(matrix(0, ncol = 7, nrow = nrow(team_info)))
colnames(results) = c("team", "starting_elo", "ending_elo", "actual_wins", "average_wins", "division_titles", "residuals")
results$team = team_info$team

win_totals = data.frame(matrix(0, ncol = nrow(team_info), nrow = iterations))
colnames(win_totals) = team_info$team

for(i in 1:iterations) {
    if(i %% 100 == 0) {print(i)}
    season_stats = team_info[,which(colnames(team_info) != "inaugural_season")]
    season_stats$wins = 0
    season_stats$rand = runif(nrow(team_info))
    
    for(j in 1:nrow(season_schedule)) {
        home_index = which(season_stats$team == season_schedule$home_team[j])
        away_index = which(season_stats$team == season_schedule$away_team[j])
        
        home_elo = season_stats$rating[home_index]
        away_elo = season_stats$rating[away_index]
        
        win_prob = 1 / (10^((away_elo - (home_elo + hfa*season_schedule$location[j]))/400) + 1)
        u = runif(1)  
        
        if(u < win_prob) {
            season_stats$wins[home_index] = season_stats$wins[home_index] + 1
        } else {
            season_stats$wins[away_index] = season_stats$wins[away_index] + 1
        }
    
        score_diff = abs(season_schedule$home_score[j] - season_schedule$away_score[j])
        
        if(season_schedule$home_score[j] > season_schedule$away_score[j]) { 
          home_result = 1  # Home team wins
        } else if(season_schedule$home_score[j] < season_schedule$away_score[j]) { 
          home_result = 0 
        } else { 
          home_result = 0.5 
        }
        
        home_elo_adjustment = weight * log(score_diff + 1 + tie_adj) * (home_result - win_prob)
        
        season_stats$rating[home_index] = season_stats$rating[home_index] + home_elo_adjustment
        season_stats$rating[away_index] = season_stats$rating[away_index] - home_elo_adjustment
    
        if(i == 1) {
            if(season_schedule$home_score[j] > season_schedule$away_score[j]) {
                results$actual_wins[home_index] = results$actual_wins[home_index] + 1
            } else if(season_schedule$home_score[j] < season_schedule$away_score[j]) {
                results$actual_wins[away_index] = results$actual_wins[away_index] + 1
            } else {
                results$actual_wins[home_index] = results$actual_wins[home_index] + 0.5
                results$actual_wins[away_index] = results$actual_wins[away_index] + 0.5
            }
        }
    }

    division_winners = data.frame(matrix(ncol = 6, nrow = 0))
    colnames(division_winners) = c("team", "conference", "division", "rating", "wins", "rand")
  
    for(div in divisions) {
        div_standings = season_stats[which(season_stats$division == div),]  
        div_standings = div_standings[order(-div_standings$wins, -div_standings$rand),]  # Sort division by wins and random number
        division_winners = rbind(division_winners, div_standings[1,])  
    }
  
    win_totals[i,] = t(season_stats[5])
    
    results$average_wins = results$average_wins + season_stats$wins
  
    for(team in division_winners$team) {
        index = which(season_stats$team == team) 
        results$division_titles[index] = results$division_titles[index] + 1 
    }
}
 
results$starting_elo = team_info$rating
results$ending_elo = season_stats$rating
results$average_wins = results$average_wins/iterations
results$division_titles = results$division_titles/iterations
results$residuals = results$actual_wins - results$average_wins

```

Problem 2a
```{r}
print(results)
```


Problem 2b

```{r}
subset_results = results[results$actual_wins > 0, ]
residuals = subset_results$actual_wins - subset_results$average_wins

hist(residuals, main = "Histogram of Residuals", xlab = "Residuals")
plot(subset_results$actual_wins, residuals, main = "Residuals vs. Actual Wins", xlab = "Actual Wins", ylab = "Residuals", pch = 19)
abline(h = 0, col = "red")
plot(subset_results$average_wins, subset_results$actual_wins, main = "Simulated Wins vs. Actual Wins", xlab = "Simulated Wins", ylab = "Actual Wins", pch = 19)

```

Read in data for Problem 3

```{r}
set.seed(7)

scores <- read.table("epl_data.csv", header = TRUE, sep = ",")

team_info <- read.table("epl_initial_elos.csv", header = TRUE, sep = ",")

simulated_season <- 2017
iterations <- 2500
weight <- 19.9
hfa <- 83.64

if (sum(scores$tie) > 0) {
    tie_adj <- 0.5 
} else {
    tie_adj <- 0
}

conferences <- na.omit(unique(team_info$conference))
divisions <- na.omit(unique(team_info$division))

season_schedule <- scores[which(scores$season == simulated_season & scores$game_type == "r"),]

results <- data.frame(matrix(0, ncol = 6, nrow = nrow(team_info)))
colnames(results) <- c("team", "starting_elo", "ending_elo", "actual_points", "average_points", "division_titles")
results$team <- team_info$team

point_totals <- data.frame(matrix(0, ncol = nrow(team_info), nrow = iterations))
colnames(point_totals) <- team_info$team

for (i in 1:iterations) {
    season_stats <- team_info[, which(colnames(team_info) != "inaugural_season")]
    season_stats$points <- 0
    season_stats$rand <- runif(nrow(team_info))
    
    for (j in 1:nrow(season_schedule)) {
        home_index <- which(season_stats$team == season_schedule$home_team[j])
        away_index <- which(season_stats$team == season_schedule$away_team[j])
        
        home_elo <- season_stats$rating[home_index]
        away_elo <- season_stats$rating[away_index]
        
        tie_prob <- (1 / (sqrt(4 * pi))) * exp(-((away_elo - (home_elo + hfa * season_schedule$location[j]))^2 / 160000))
        win_prob <- 1 / (10^((away_elo - (home_elo + hfa * season_schedule$location[j])) / 400) + 1) - 0.50 * tie_prob
        u <- runif(1)
    
        if (u < win_prob) {  
            season_stats$points[home_index] <- season_stats$points[home_index] + 3
        } else if (u < win_prob + tie_prob) { 
            season_stats$points[home_index] <- season_stats$points[home_index] + 1
            season_stats$points[away_index] <- season_stats$points[away_index] + 1
        } else {  
            season_stats$points[away_index] <- season_stats$points[away_index] + 3
        }

        score_diff <- abs(season_schedule$home_score[j] - season_schedule$away_score[j])   
        
        if (season_schedule$home_score[j] > season_schedule$away_score[j]) { 
            home_result <- 1  
        } else if (season_schedule$home_score[j] < season_schedule$away_score[j]) { 
            home_result <- 0  
        } else { 
            home_result <- 0.5  
        }
    
        home_elo_adjustment <- weight * log(score_diff + 1 + tie_adj) * (home_result - (win_prob + 0.5 * tie_prob))
        
        season_stats$rating[home_index] <- season_stats$rating[home_index] + home_elo_adjustment
        season_stats$rating[away_index] <- season_stats$rating[away_index] - home_elo_adjustment
    }
  
    division_winners <- data.frame(matrix(ncol = 6, nrow = 0))
    colnames(division_winners) <- c("team", "conference", "division", "rating", "wins", "rand")
    
    # For each division
    for (div in divisions) {
        div_standings <- season_stats[which(season_stats$division == div),] 
        div_standings <- div_standings[order(-div_standings$points, -div_standings$rand),]  
        division_winners <- rbind(division_winners, div_standings[1,])  
    }
  
    point_totals[i,] <- t(season_stats[5])
    
    results$average_points <- results$average_points + season_stats$points
    
    for (team in division_winners$team) {
        index <- which(season_stats$team == team)  
        results$division_titles[index] <- results$division_titles[index] + 1  
    }
}

results$starting_elo <- team_info$rating
results$ending_elo <- season_stats$rating
results$average_points <- results$average_points / iterations
results$division_titles <- results$division_titles / iterations

elo_point_value = 0.042

exp_mov = ((home_elo + hfa*scores$location[i]) - away_elo) * elo_point_value
    
if(scores$home_score[i] - scores$away_score[i] > exp_mov) { 
    home_result = 1  # Home team wins
} else {
    home_result = 0  # Tie
}
    
home_elo_adjustment = weight * log(abs(exp_mov - score_diff) + 1) * (home_result - .5)
```

Problem 3a
```{r}
print(results)
```


Problem 3b

```{r}
teams_of_interest <- c("Manchester City", "Crystal Palace", "West Bromwich Albion")
team_points <- point_totals[, teams_of_interest]

hist(team_points[, 1], main = paste("Point Totals for", teams_of_interest[1]), xlab = "Points")

hist(team_points[, 2], main = paste("Point Totals for", teams_of_interest[2]), xlab = "Points")

hist(team_points[, 3], main = paste("Point Totals for", teams_of_interest[3]), xlab = "Points")

```
